# Generated by Django 4.2.5 on 2023-09-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='ratings',
            new_name='rating',
        ),
    ]
