# Generated by Django 4.2.5 on 2023-09-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_ratings_rating_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',)},
        ),
    ]
